### ISSUE TITLE
Question about Figure 2

### ISSUE THREAD

**Issue by ayakatakuriko** [bbbbby-99/WaH-NeRF#1]
Thank you for your great work!
I'm confused about the black solid box in Fig.2.
What does its height mean?
Why is the height different between Fig.2 (c) and (d)?
I would be grateful if you would explain about that.

**Comment by bbbbby-99** [comment]
Hello, 
Thank you for your interest in our work.
 "Height" represents the uncertainty in color value prediction during volume rendering. The closer RGBMSE is to 0, the more it indicates that the predicted color values at sampling points are close to the ground truth (non-zero weight parts). In fact, the height of the box reflects the maximum value of RGBMSE in the non-zero weight parts. Therefore, the height of the box can be used to represent the uncertainty in color value prediction. 
In an ideal scenario, the height of the box should be close to 0, as Fig.2 (a) and (b).
In our work, a semi-supervised approach effectively mitigates this issue.
